version: '3.7'

services:
  api:
    build: ./api
    ports: 
      - 8000:8000
    volumes:
      - ./api:/api

  react:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend